-- This file was refactored into migrations.
-- See supabase/migrations/ for the schema definitions.
--
-- Local auth users are created via:
--   bash scripts/reset-local-admin-password.sh
-- Do not insert raw rows into auth.users here — invalid password hashes break login.
--
-- Demo groups/markets are seeded by scripts/seed-e2e-fixtures.ts when running E2E.
