#!/usr/bin/env bash
# Cloud Agent start phase for Anymarkt (qbet).
# Runs on every boot: brings up Docker + the local Supabase stack, applies
# migrations, and materialises the local .env files. Idempotent and tolerant
# of restarts. The Expo web server runs separately in the "expo-web" terminal.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
export PATH="/usr/local/bin:$HOME/.deno/bin:$PATH"

log() { echo "[start] $*"; }

# ── Docker daemon ──────────────────────────────────────────────────────────
bash .cursor/docker-up.sh

# ── Local Supabase stack ───────────────────────────────────────────────────
if supabase status >/dev/null 2>&1; then
  log "Supabase already running"
else
  log "Starting local Supabase stack (first boot pulls images)"
  supabase start
fi

# Ensure migrations are applied (no-op when already up to date).
supabase migration up --local >/dev/null 2>&1 || true

# ── App env (.env) ─────────────────────────────────────────────────────────
if [[ ! -f .env ]]; then
  log "Writing .env from local Supabase status"
  # shellcheck disable=SC2046
  eval "$(supabase status -o env)"
  cat > .env <<EOF
# Generated by .cursor/start.sh — local development values only.
EXPO_PUBLIC_ADMIN_EMAIL=admin@example.com
EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_your_publishable_key
EXPO_PUBLIC_SUPABASE_URL=${API_URL:-http://127.0.0.1:54321}
EXPO_PUBLIC_SUPABASE_KEY=${ANON_KEY}
EXPO_PUBLIC_APP_URL=http://localhost:8081
EXPO_PUBLIC_LAUNCH_JURISDICTION=EC
EXPO_PUBLIC_BETA_REQUIRED=true
EXPO_PUBLIC_DEBUG_LOGS=true
EOF
fi

# ── Edge-function env (used by `supabase functions serve`) ──────────────────
if [[ ! -f supabase/functions/.env && -f supabase/functions/.env.example ]]; then
  cp supabase/functions/.env.example supabase/functions/.env
fi

log "start complete — Supabase up at http://127.0.0.1:54321 (Studio :54323, Mailpit :54324)"
log "The Expo web app boots in the 'expo-web' terminal at http://localhost:8081"
