#!/usr/bin/env bash
# Start dual Stripe CLI listeners for local E2E and write webhook secrets.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v stripe >/dev/null 2>&1; then
  echo "Stripe CLI required: https://stripe.com/docs/stripe-cli"
  exit 1
fi

SECRETS_FILE="${STRIPE_SECRETS_FILE:-tests/e2e/.stripe-secrets.env}"
PIDS_FILE="${STRIPE_PIDS_FILE:-tests/e2e/.stripe-listen.pids}"
PAYMENTS_LOG="$(mktemp)"
IDENTITY_LOG="$(mktemp)"

mkdir -p "$(dirname "$SECRETS_FILE")"

cleanup() {
  if [[ "${STRIPE_LISTEN_FOREGROUND:-1}" == "1" ]]; then
    if [[ -f "$PIDS_FILE" ]]; then
      while read -r pid; do
        [[ -n "$pid" ]] && kill "$pid" 2>/dev/null || true
      done < "$PIDS_FILE"
      rm -f "$PIDS_FILE"
    fi
  fi
  rm -f "$PAYMENTS_LOG" "$IDENTITY_LOG"
}
trap cleanup EXIT INT TERM

wait_for_secret() {
  local log_file="$1"
  local label="$2"
  local secret=""
  for _ in $(seq 1 45); do
    secret="$(grep -oE 'whsec_[a-zA-Z0-9]+' "$log_file" 2>/dev/null | head -1 || true)"
    if [[ -n "$secret" ]]; then
      echo "$secret"
      return 0
    fi
    sleep 1
  done
  echo "Timed out waiting for $label webhook secret" >&2
  return 1
}

echo "Starting Stripe payment webhook listener..."
stripe listen \
  --events checkout.session.completed,payment_intent.succeeded,payment_intent.payment_failed \
  --forward-to http://127.0.0.1:54321/functions/v1/stripe-webhook \
  >"$PAYMENTS_LOG" 2>&1 &
PAYMENTS_PID=$!
echo "$PAYMENTS_PID" >"$PIDS_FILE"

echo "Starting Stripe Identity webhook listener..."
stripe listen \
  --events identity.verification_session.verified,identity.verification_session.requires_input,identity.verification_session.canceled \
  --forward-to http://127.0.0.1:54321/functions/v1/stripe-identity-webhook \
  >"$IDENTITY_LOG" 2>&1 &
IDENTITY_PID=$!
echo "$IDENTITY_PID" >>"$PIDS_FILE"

PAYMENTS_SECRET="$(wait_for_secret "$PAYMENTS_LOG" "payments")"
IDENTITY_SECRET="$(wait_for_secret "$IDENTITY_LOG" "identity")"

cat >"$SECRETS_FILE" <<EOF
# Generated by scripts/stripe-e2e-listen.sh — do not commit
STRIPE_WEBHOOK_SECRET=$PAYMENTS_SECRET
STRIPE_IDENTITY_WEBHOOK_SECRET=$IDENTITY_SECRET
EOF

echo "Wrote webhook secrets to $SECRETS_FILE"
echo "  STRIPE_WEBHOOK_SECRET=${PAYMENTS_SECRET:0:12}..."
echo "  STRIPE_IDENTITY_WEBHOOK_SECRET=${IDENTITY_SECRET:0:12}..."
echo ""
echo "Merge into supabase/functions/.env before functions serve, or let run-local-e2e.sh do it."
echo "Listeners running (PIDs $PAYMENTS_PID, $IDENTITY_PID). Press Ctrl+C to stop."

if [[ "${STRIPE_LISTEN_FOREGROUND:-1}" == "1" ]]; then
  wait
else
  echo "Background mode — listeners left running (PIDs in $PIDS_FILE)"
fi
